---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-continuous-upload-proxy-data
  namespace: continuous-upload
  labels:
    pv: pv-continuous-upload-proxy-data
spec:
  capacity:
    storage: STORAGE_SIZE
  accessModes:
    - ReadWriteOnce
  nfs:
    server: HOST_DATA_SERVER
    path: "HOST_DATA_DIR"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-continuous-upload-proxy-data
  namespace: continuous-upload
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: STORAGE_SIZE
  selector:
    matchLabels:
      pv: pv-continuous-upload-proxy-data